// /为根路由，@代表 pages目录

export default [
    {
        path: '/', component: '@/layouts/index', routes: [
            { path: '/404', component: '@/pages/404' },
            { path: '/403', component: '@/pages/403' },
            { path: '/login', component: '@/pages/login' },
            { path: '/forgot', component: '@/pages/forgot' },
            { path: '/workbench', component: '@/pages/workbench' },
            { path: '/dashboard', component: '@/pages/dashboard' },
            { path: '/operatecenter/creditgranting', component: '@/pages/operatecenter/creditgranting' },
            { path: '/operatecenter/creditgranting/detail', component: '@/pages/operatecenter/creditgranting/detail' },
            { path: '/operatecenter/creditgranting/view', component: '@/pages/operatecenter/creditgranting/view' },
            { path: '/operatecenter/withdrawal', component: '@/pages/operatecenter/withdrawal' },
            { path: '/operatecenter/withdrawal/detail', component: '@/pages/operatecenter/withdrawal/detail' },
            { path: '/operatecenter/withdrawal/view', component: '@/pages/operatecenter/withdrawal/view' },
            { path: '/operatecenter/scene', component: '@/pages/operatecenter/scene' },
            { path: '/operatecenter/scene/creditgranting/detail', component: '@/pages/operatecenter/creditgranting/detail' },
            { path: '/operatecenter/scene/creditgranting/view', component: '@/pages/operatecenter/creditgranting/view' },
            { path: '/operatecenter/scene/withdrawal/detail', component: '@/pages/operatecenter/withdrawal/detail' },
            { path: '/operatecenter/scene/withdrawal/view', component: '@/pages/operatecenter/withdrawal/view' },
            { path: '/operatecenter/loaned', component: '@/pages/operatecenter/loaned' },
            { path: '/operatecenter/loaned/repaymentplan', component: '@/pages/operatecenter/loaned/repaymentplan' },
            { path: '/operatecenter/loaned/customercare', component: '@/pages/operatecenter/loaned/customercare' },
            { path: '/operatecenter/loaned/loancollection', component: '@/pages/operatecenter/loaned/loancollection' },
            { path: '/operatecenter/report', component: '@/pages/operatecenter/report' },
            { path: '/operatecenter/uniting', component: '@/pages/operatecenter/uniting' },
            { path: '/operatecenter/uniting/detail', component: '@/pages/operatecenter/uniting/detail' },
            { path: '/operatecenter/uniting/decode', component: '@/pages/operatecenter/uniting/decode' },
            { path: '/operatecenter/uniting/creditgranting/view', component: '@/pages/operatecenter/creditgranting/view' },
            { path: '/operatecenter/uniting/withdrawal/view', component: '@/pages/operatecenter/withdrawal/view' },
            { path: '/customercenter/customer', component: '@/pages/customercenter/customer' },
            { path: '/customercenter/customer/detail', component: '@/pages/customercenter/customer/detail' },
            { path: '/customercenter/patient', component: '@/pages/customercenter/patient' },
            { path: '/customercenter/patient/detail', component: '@/pages/customercenter/patient/detail' },
            // { path: '/customercenter/riskportrait', component: '@/pages/customercenter/riskportrait' },
            { path: '/customercenter/chat', component: '@/pages/customercenter/chat' },
            { path: '/chainbrowser', component: '@/pages/chainbrowser' },
            { path: '/chainbrowser/height', component: '@/pages/chainbrowser/height' },
            { path: '/chainbrowser/transaction', component: '@/pages/chainbrowser/transaction' },
            { path: '/productcenter/apparatus', component: '@/pages/productcenter/apparatus' },
            { path: '/productcenter/capital', component: '@/pages/productcenter/capital' },
            { path: '/productcenter/capital/create', component: '@/pages/productcenter/capital/create' },
            { path: '/productcenter/contracttemplate', component: '@/pages/productcenter/contracttemplate' },
            { path: '/productcenter/hospital', component: '@/pages/productcenter/hospital' },
            { path: '/productcenter/hospital/create', component: '@/pages/productcenter/hospital/create' },
            { path: '/productcenter/hospital/update', component: '@/pages/productcenter/hospital/update' },
            { path: '/productcenter/hospital/routes', component: '@/pages/productcenter/hospital/routes' },
            { path: '/productcenter/hospital/detail', component: '@/pages/productcenter/hospital/detail' },
            { path: '/productcenter/product', component: '@/pages/productcenter/product' },

            { path: '/riskcenter/decision', component: '@/pages/riskcenter/decision' },
            { path: '/riskcenter/variable', component: '@/pages/riskcenter/variable' },
            { path: '/riskcenter/variable/catalog', component: '@/pages/riskcenter/variable/catalog' },
            { path: '/riskcenter/variable/catalog/field', component: '@/pages/riskcenter/variable/catalog/field' },
            { path: '/riskcenter/decision/update', component: '@/pages/riskcenter/decision/update' },

            { path: '/datacenter/ledgerinfo', component: '@/pages/datacenter/ledgerinfo' },
            { path: '/datacenter/ledgersummary', component: '@/pages/datacenter/ledgersummary' },

            { path: '/configurecenter/menu', component: '@/pages/configurecenter/menu' },
            { path: '/configurecenter/role', component: '@/pages/configurecenter/role' },
            { path: '/configurecenter/organization', component: '@/pages/configurecenter/organization' },
            { path: '/configurecenter/clearaccount', component: '@/pages/configurecenter/clearaccount' },
            { path: '/configurecenter/clientversion', component: '@/pages/configurecenter/clientversion' },
            { path: '/configurecenter/announcement', component: '@/pages/configurecenter/announcement' },
            { path: '/configurecenter/help', component: '@/pages/configurecenter/help' },
            { path: '/configurecenter/help/create', component: '@/pages/configurecenter/help/create' },
            { path: '/configurecenter/help/detail', component: '@/pages/configurecenter/help/detail' },
            { path: '/configurecenter/help/update', component: '@/pages/configurecenter/help/update' },

            { path: '/workflow/manager', component: '@/pages/workflow/manager' },
            { path: '/workflow/manager/design', component: '@/pages/workflow/manager/design' },
        ]
    },
]